language: cpp
jobs:
  include:
    - name: "Mods"
      os: linux
      dist: xenial
      install:
        - . ./lib.sh
      script:
        - mkdir -p /tmp/WORKSPACE/work
        - pushd /tmp/WORKSPACE/work
        - job_mods
        - mkdir -p /tmp/WORKSPACE/DEPLOY/mods
        - cp -v * /tmp/WORKSPACE/DEPLOY/mods
        - popd
    - name: "MacOSX Client"
      os: osx
      osx_image: xcode8
      install:
        - brew update
        - . ./lib.sh
        - env -i bash -l -c "brew install $(minetest_osx_builddeps)"
      script:
        - mkdir -p /tmp/WORKSPACE
        - pushd /tmp/WORKSPACE
        - get_minetest
        - build_minetest_client_osx
        - mkdir -p /tmp/WORKSPACE/DEPLOY/client/macosx
        - cp -rv ./minetest/*.zip /tmp/WORKSPACE/DEPLOY/client/macosx/minetest.zip
        - popd
    - name: "GNU/Linux AMD64 Client"
      os: linux
      dist: xenial
      install:
        - . ./lib.sh
        - sudo apt-get update && sudo apt-get remove -y mysql-server-5.7 $(COMMENT "travis ci bug") && sudo apt-get dist-upgrade -y # because some libraries will be copied to AppImage
        - install_minetest_debian_builddeps
      script:
        - mkdir -p /tmp/WORKSPACE
        - pushd /tmp/WORKSPACE
        - get_minetest
        - build_minetest_client_gnulinux_amd64
        - mkdir -p /tmp/WORKSPACE/DEPLOY/client/gnulinux/amd64
        - cp ./minetest/minetest.AppImage /tmp/WORKSPACE/DEPLOY/client/gnulinux/amd64
        - popd
    - name: "GNU/Linux AMD64 Server"
      os: linux
      dist: xenial
      install:
        - . ./lib.sh
        - sudo apt-get update && sudo apt-get remove -y mysql-server-5.7 $(COMMENT "travis ci bug") && sudo apt-get dist-upgrade -y # because some libraries will be copied to AppImage
        - install_minetest_debian_builddeps
      script:
        - mkdir -p /tmp/WORKSPACE
        - pushd /tmp/WORKSPACE
        - get_minetest
        - build_minetest_server_gnulinux_amd64
        - mkdir -p /tmp/WORKSPACE/DEPLOY/server/gnulinux/amd64
        - cp ./minetest/minetestserver.AppImage /tmp/WORKSPACE/DEPLOY/server/gnulinux/amd64
        - popd
    - name: "Windows AMD64 Client"
      os: linux
      dist: xenial
      install:
        - sudo apt-get update
        - . ./lib.sh
      script:
        - mkdir -p /tmp/WORKSPACE
        - pushd /tmp/WORKSPACE
        - CONFIG_WIN_ARCH=x86_64
        - install_minetest_mingw_builddeps__and__build__ubuntu1604
        - mkdir -p /tmp/WORKSPACE/DEPLOY/client/windows/amd64
        - cp ./minetest/minetest.zip /tmp/WORKSPACE/DEPLOY/client/windows/amd64
        - popd
    - name: "Windows i686 Client"
      os: linux
      dist: xenial
      install:
        - sudo apt-get update
        - . ./lib.sh
      script:
        - mkdir -p /tmp/WORKSPACE
        - pushd /tmp/WORKSPACE
        - CONFIG_WIN_ARCH=i686
        - install_minetest_mingw_builddeps__and__build__ubuntu1604
        - mkdir -p /tmp/WORKSPACE/DEPLOY/client/windows/i686
        - cp ./minetest/minetest.zip /tmp/WORKSPACE/DEPLOY/client/windows/i686
        - popd
    - name: "Android Client"
      os: linux
      dist: xenial
      cache:
        directories:
          # This signing key is only used to make Android happy, not for signing.
          - $HOME/apk-signing-key
      install:
        - wget --quiet -O ~/sdk-tools-linux.zip https://dl.google.com/android/repository/sdk-tools-linux-4333796.zip
        - unzip -q ~/sdk-tools-linux.zip -d ~/android-sdk-linux
        - rm ~/sdk-tools-linux.zip
        - export ANDROID_HOME="$HOME/android-sdk-linux"
        - export PATH="$PATH:$ANDROID_HOME/tools/bin"
        - ndk_version=r16b
        - wget --quiet -O "$HOME/android-ndk-${ndk_version}.zip" "https://dl.google.com/android/repository/android-ndk-${ndk_version}-linux-x86_64.zip"
        - unzip -q "$HOME/android-ndk-${ndk_version}.zip" -d ~
        - rm "$HOME/android-ndk-${ndk_version}.zip"
        - export ANDROID_NDK_HOME="$HOME/android-ndk-${ndk_version}"
        - export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
        - echo y | sdkmanager "build-tools;29.0.2" >/dev/null
        - export PATH="$PATH:$ANDROID_HOME/build-tools/29.0.2"
        - echo y | sdkmanager "platforms;android-29" >/dev/null
      script:
        - . ./lib.sh
        - mkdir -p /tmp/WORKSPACE
        - pushd /tmp/WORKSPACE
        - get_minetest
        - rm -fr ./minetest/games/minetest_game/.git
        - echo "ndk.dir = $ANDROID_NDK_HOME" > ./minetest/build/android/local.properties
        - echo "sdk.dir = $ANDROID_HOME" >> ./minetest/build/android/local.properties
        - pushd ./minetest/build/android
        - make release -j4 2>&1 | cat
        - mkdir -p /tmp/WORKSPACE/DEPLOY/client/android
        - zipalign -p 4 ./build/outputs/apk/release/Minetest-release-unsigned.apk /tmp/WORKSPACE/DEPLOY/client/android/minetest.apk
        - mkdir -p ~/apk-signing-key
        - if [ ! -f ~/apk-signing-key/key.keystore ];then yes | keytool -genkey -v -keystore ~/apk-signing-key/key.keystore -keyalg RSA -keysize 2048 -validity 327680 -alias key -storepass storepass;fi
        - apksigner sign --ks ~/apk-signing-key/key.keystore --ks-key-alias key --ks-pass pass:storepass /tmp/WORKSPACE/DEPLOY/client/android/minetest.apk
        - popd
        - popd

after_success:
  - |
    if [ -n "${PRIVATE_KEY_BASE64}" ] && [ -d /tmp/WORKSPACE/DEPLOY ] ;then while true; do
      cd /tmp/WORKSPACE
      git config --global user.email tsao-chi@the-lingo.org
      git config --global user.name 'ㄗㄠˋ ㄑㄧˊ'
      echo "${PRIVATE_KEY_BASE64}" | base64 --decode > ~/.ssh/id_rsa
      chmod 600 ~/.ssh/id_rsa
      echo '|1|k7dX5r7i2g/3DPILXRo9cZfb4Fo=|4UYUWLg6aLAK/VRgqvuGotOcuNg= ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==' > ~/.ssh/known_hosts
      rm -fr /tmp/WORKSPACE/deploy_repo
      git clone --depth 1 git@github.com:The-Unstable-World/binary.git /tmp/WORKSPACE/deploy_repo
      cd /tmp/WORKSPACE/deploy_repo
      cp -rv /tmp/WORKSPACE/DEPLOY/* ./
      git add .
      git commit -m 'deploy'
      git push && break
    done; fi
