name: CI
on:
  push:
    branches:
      - master
#  schedule:
#    - cron:  '0 */1 * * *'

jobs:
  mods:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: |
        . ./lib.sh
        mkdir -p /tmp/WORKSPACE/DEPLOY/mods &&
        pushd /tmp/WORKSPACE/DEPLOY/mods &&
        job_mods &&
        popd
    - name: Publish
      uses: actions/upload-artifact@v2-preview
      with:
        name: mods
        path: /tmp/WORKSPACE/DEPLOY
  games:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: |
        . ./lib.sh
        mkdir -p /tmp/WORKSPACE/DEPLOY/games &&
        pushd /tmp/WORKSPACE/DEPLOY/games &&
        job_capturetheflag &&
        popd
    - name: Publish
      uses: actions/upload-artifact@v2-preview
      with:
        name: games
        path: /tmp/WORKSPACE/DEPLOY
  amd64-alpine-server:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: |
        mkdir -p /tmp/WORKSPACE &&
        docker run -i --rm --workdir "$PWD" -v "$PWD:$PWD" -v "/tmp/WORKSPACE:/tmp/WORKSPACE" alpine sh << 'EOF'
          export APPIMAGE_EXTRACT_AND_RUN=1
          . ./lib.sh
          CONFIG_APPIMAGE_TOOLS_ARCH=x86_64
          CONFIG_ALPINE_ROOTFS_ARCH=x86_64
          install_minetest_alpine_builddeps_nosudo &&
          cd /tmp/WORKSPACE &&
          get_minetest &&
          build_minetest_server_gnulinux &&
          build_appimage_install_builddeps_alpine_nosudo &&
          bundle_minetest_server_gnulinux_appimage_alpine &&
          mkdir -p /tmp/WORKSPACE/DEPLOY/server/gnulinux/amd64 &&
          cp ./minetest/minetestserver.AppImage /tmp/WORKSPACE/DEPLOY/server/gnulinux/amd64/minetestserver_alpine.AppImage
        EOF
    - name: Publish
      uses: actions/upload-artifact@v2-preview
      with:
        name: amd64-alpine-server
        path: /tmp/WORKSPACE/DEPLOY
  mac-client:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install
      run: |
        . ./lib.sh &&
        RETRY brew update &&
        install_osx_coreutils_and_set_PATH &&
        install_minetest_osx_builddeps
    - name: Build
      run: |
        mkdir -p /tmp/WORKSPACE &&
        pushd /tmp/WORKSPACE &&
        get_minetest &&
        build_minetest_client_osx &&
        mkdir -p /tmp/WORKSPACE/DEPLOY/client/macosx &&
        cp -rv ./minetest/*.zip /tmp/WORKSPACE/DEPLOY/client/macosx/minetest.zip &&
        popd
    - name: Publish
      uses: actions/upload-artifact@v2-preview
      with:
        name: mac-client
        path: /tmp/WORKSPACE/DEPLOY
  mac-client-cheat:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install
      run: |
        . ./lib.sh &&
        RETRY brew update &&
        install_osx_coreutils_and_set_PATH &&
        install_minetest_osx_builddeps
    - name: Build
      run: |
        mkdir -p /tmp/WORKSPACE &&
        pushd /tmp/WORKSPACE &&
        get_minetest &&
        apply_cheat_patch &&
        (cd minetest && git add . && git diff --cached) &&
        build_minetest_client_osx &&
        mkdir -p /tmp/WORKSPACE/DEPLOY/cheat_client/macosx &&
        cp -rv ./minetest/*.zip /tmp/WORKSPACE/DEPLOY/cheat_client/macosx/minetest.zip &&
        popd
    - name: Publish
      uses: actions/upload-artifact@v2-preview
      with:
        name: mac-client-cheat
        path: /tmp/WORKSPACE/DEPLOY
