name: CI
on:
  push:
    branches:
      - master
#  schedule:
#    - cron:  '0 */1 * * *'

jobs:
  mods:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: |
        . ./lib.sh
        mkdir -p /tmp/WORKSPACE/DEPLOY/mods &&
        pushd /tmp/WORKSPACE/DEPLOY/mods &&
        job_mods &&
        popd
    - name: Publish
      uses: actions/upload-artifact@v2-preview
      with:
        name: mods
        path: /tmp/WORKSPACE/DEPLOY
  games:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: |
        . ./lib.sh
        mkdir -p /tmp/WORKSPACE/DEPLOY/games &&
        pushd /tmp/WORKSPACE/DEPLOY/games &&
        job_capturetheflag &&
        popd
    - name: Publish
      uses: actions/upload-artifact@v2-preview
      with:
        name: games
        path: /tmp/WORKSPACE/DEPLOY
  amd64-alpine-server:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: |
        mkdir -p /tmp/WORKSPACE &&
        docker run -i --rm --workdir "$PWD" -v "$PWD:$PWD" -v "/tmp/WORKSPACE:/tmp/WORKSPACE" alpine sh << 'EOF'
          export APPIMAGE_EXTRACT_AND_RUN=1
          . ./lib.sh
          CONFIG_APPIMAGE_TOOLS_ARCH=x86_64
          CONFIG_ALPINE_ROOTFS_ARCH=x86_64
          install_minetest_alpine_builddeps_nosudo &&
          cd /tmp/WORKSPACE &&
          get_minetest &&
          build_minetest_server_gnulinux &&
          build_appimage_install_builddeps_alpine_nosudo &&
          bundle_minetest_server_gnulinux_appimage_alpine &&
          mkdir -p /tmp/WORKSPACE/DEPLOY/server/gnulinux/amd64 &&
          cp ./minetest/minetestserver.AppImage /tmp/WORKSPACE/DEPLOY/server/gnulinux/amd64/minetestserver_alpine.AppImage
        EOF
    - name: Publish
      uses: actions/upload-artifact@v2-preview
      with:
        name: amd64-alpine-server
        path: /tmp/WORKSPACE/DEPLOY
  amd64-linux-server:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: |
        mkdir -p /tmp/WORKSPACE &&
        docker run -i --rm --workdir "$PWD" -v "$PWD:$PWD" -v "/tmp/WORKSPACE:/tmp/WORKSPACE" centos:7 bash << 'EOF'
          export APPIMAGE_EXTRACT_AND_RUN=1
          . ./lib.sh
          CONFIG_APPIMAGE_TOOLS_ARCH=x86_64
          RETRY yum update -y &&
          install_minetest_centos7_builddeps_nosudo &&
          cd /tmp/WORKSPACE &&
          get_minetest &&
          build_minetest_server_gnulinux &&
          get_appimage_and_linuxdeploy &&
          bundle_minetest_server_gnulinux_appimage &&
          mkdir -p /tmp/WORKSPACE/DEPLOY/server/gnulinux/amd64 &&
          cp ./minetest/minetestserver.AppImage /tmp/WORKSPACE/DEPLOY/server/gnulinux/amd64
        EOF
    - name: Publish
      uses: actions/upload-artifact@v2-preview
      with:
        name: amd64-linux-server
        path: /tmp/WORKSPACE/DEPLOY
  amd64-archlinux-server:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: |
        mkdir -p /tmp/WORKSPACE &&
        docker run -i --rm --workdir "$PWD" -v "$PWD:$PWD" -v "/tmp/WORKSPACE:/tmp/WORKSPACE" archlinux/base bash << 'EOF'
          export APPIMAGE_EXTRACT_AND_RUN=1
          . ./lib.sh
          CONFIG_APPIMAGE_TOOLS_ARCH=x86_64
          install_minetest_archlinux_builddeps_nosudo &&
          cd /tmp/WORKSPACE &&
          get_minetest &&
          build_minetest_server_gnulinux &&
          get_appimage_and_linuxdeploy &&
          bundle_minetest_server_gnulinux_appimage &&
          mkdir -p /tmp/WORKSPACE/DEPLOY/server/gnulinux/amd64 &&
          cp ./minetest/minetestserver.AppImage /tmp/WORKSPACE/DEPLOY/server/gnulinux/amd64/minetestserver_archlinux.AppImage
        EOF
    - name: Publish
      uses: actions/upload-artifact@v2-preview
      with:
        name: amd64-archlinux-server
        path: /tmp/WORKSPACE/DEPLOY
  amd64-alpine-client:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: |
        mkdir -p /tmp/WORKSPACE &&
        docker run -i --rm --workdir "$PWD" -v "$PWD:$PWD" -v "/tmp/WORKSPACE:/tmp/WORKSPACE" alpine sh << 'EOF'
          export APPIMAGE_EXTRACT_AND_RUN=1
          . ./lib.sh
          CONFIG_APPIMAGE_TOOLS_ARCH=x86_64
          CONFIG_ALPINE_ROOTFS_ARCH=x86_64
          install_minetest_alpine_builddeps_nosudo &&
          cd /tmp/WORKSPACE &&
          get_minetest &&
          build_minetest_client_gnulinux &&
          build_appimage_install_builddeps_alpine_nosudo &&
          bundle_minetest_client_gnulinux_appimage_alpine &&
          mkdir -p /tmp/WORKSPACE/DEPLOY/client/gnulinux/amd64 &&
          cp ./minetest/minetest.AppImage /tmp/WORKSPACE/DEPLOY/client/gnulinux/amd64/minetest_alpine.AppImage
        EOF
    - name: Publish
      uses: actions/upload-artifact@v2-preview
      with:
        name: amd64-alpine-client
        path: /tmp/WORKSPACE/DEPLOY
  amd64-linux-client:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: |
        mkdir -p /tmp/WORKSPACE &&
        docker run -i --rm --workdir "$PWD" -v "$PWD:$PWD" -v "/tmp/WORKSPACE:/tmp/WORKSPACE" centos:7 bash << 'EOF'
          export APPIMAGE_EXTRACT_AND_RUN=1
          . ./lib.sh
          CONFIG_APPIMAGE_TOOLS_ARCH=x86_64
          RETRY yum update -y &&
          install_minetest_centos7_builddeps_nosudo &&
          cd /tmp/WORKSPACE &&
          get_minetest &&
          build_minetest_client_gnulinux &&
          get_appimage_and_linuxdeploy &&
          bundle_minetest_client_gnulinux_appimage &&
          mkdir -p /tmp/WORKSPACE/DEPLOY/client/gnulinux/amd64 &&
          cp ./minetest/minetest.AppImage /tmp/WORKSPACE/DEPLOY/client/gnulinux/amd64
        EOF
    - name: Publish
      uses: actions/upload-artifact@v2-preview
      with:
        name: amd64-linux-client
        path: /tmp/WORKSPACE/DEPLOY
  amd64-archlinux-client:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: |
        mkdir -p /tmp/WORKSPACE &&
        docker run -i --rm --workdir "$PWD" -v "$PWD:$PWD" -v "/tmp/WORKSPACE:/tmp/WORKSPACE" archlinux/base bash << 'EOF'
          export APPIMAGE_EXTRACT_AND_RUN=1
          . ./lib.sh
          CONFIG_APPIMAGE_TOOLS_ARCH=x86_64
          install_minetest_archlinux_builddeps_nosudo &&
          cd /tmp/WORKSPACE &&
          get_minetest &&
          build_minetest_client_gnulinux &&
          get_appimage_and_linuxdeploy &&
          bundle_minetest_client_gnulinux_appimage &&
          mkdir -p /tmp/WORKSPACE/DEPLOY/client/gnulinux/amd64 &&
          cp ./minetest/minetest.AppImage /tmp/WORKSPACE/DEPLOY/client/gnulinux/amd64/minetest_archlinux.AppImage
        EOF
    - name: Publish
      uses: actions/upload-artifact@v2-preview
      with:
        name: amd64-archlinux-client
        path: /tmp/WORKSPACE/DEPLOY
  amd64-linux-client-cheat:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: |
        mkdir -p /tmp/WORKSPACE &&
        docker run -i --rm --workdir "$PWD" -v "$PWD:$PWD" -v "/tmp/WORKSPACE:/tmp/WORKSPACE" centos:7 bash << 'EOF'
          export APPIMAGE_EXTRACT_AND_RUN=1
          . ./lib.sh
          CONFIG_APPIMAGE_TOOLS_ARCH=x86_64
          RETRY yum update -y &&
          install_minetest_centos7_builddeps_nosudo &&
          cd /tmp/WORKSPACE &&
          get_minetest &&
          apply_cheat_patch &&
          (cd minetest && git add . && git diff --cached) &&
          build_minetest_client_gnulinux &&
          get_appimage_and_linuxdeploy &&
          bundle_minetest_client_gnulinux_appimage &&
          mkdir -p /tmp/WORKSPACE/DEPLOY/cheat_client/gnulinux/amd64 &&
          cp ./minetest/minetest.AppImage /tmp/WORKSPACE/DEPLOY/cheat_client/gnulinux/amd64
        EOF
    - name: Publish
      uses: actions/upload-artifact@v2-preview
      with:
        name: amd64-linux-client-cheat
        path: /tmp/WORKSPACE/DEPLOY
  mac-client:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: |
        . ./lib.sh &&
        RETRY brew update &&
        install_osx_coreutils_and_set_PATH &&
        install_minetest_osx_builddeps &&
        mkdir -p /tmp/WORKSPACE &&
        pushd /tmp/WORKSPACE &&
        get_minetest &&
        build_minetest_client_osx &&
        mkdir -p /tmp/WORKSPACE/DEPLOY/client/macosx &&
        cp -rv ./minetest/*.zip /tmp/WORKSPACE/DEPLOY/client/macosx/minetest.zip &&
        popd
    - name: Publish
      uses: actions/upload-artifact@v2-preview
      with:
        name: mac-client
        path: /tmp/WORKSPACE/DEPLOY
  mac-client-cheat:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: |
        . ./lib.sh &&
        RETRY brew update &&
        install_osx_coreutils_and_set_PATH &&
        install_minetest_osx_builddeps &&
        mkdir -p /tmp/WORKSPACE &&
        pushd /tmp/WORKSPACE &&
        get_minetest &&
        apply_cheat_patch &&
        (cd minetest && git add . && git diff --cached) &&
        build_minetest_client_osx &&
        mkdir -p /tmp/WORKSPACE/DEPLOY/cheat_client/macosx &&
        cp -rv ./minetest/*.zip /tmp/WORKSPACE/DEPLOY/cheat_client/macosx/minetest.zip &&
        popd
    - name: Publish
      uses: actions/upload-artifact@v2-preview
      with:
        name: mac-client-cheat
        path: /tmp/WORKSPACE/DEPLOY
  amd64-windows-client:
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: |
        CONFIG_WIN_ARCH=x86_64
        . ./lib.sh &&
        RETRY sudo apt-get update &&
        mkdir -p /tmp/WORKSPACE &&
        pushd /tmp/WORKSPACE &&
        install_minetest_mingw_builddeps__and__build__ubuntu1604 &&
        mkdir -p /tmp/WORKSPACE/DEPLOY/client/windows/amd64 &&
        cp ./minetest/minetest.zip /tmp/WORKSPACE/DEPLOY/client/windows/amd64 &&
        popd
    - name: Publish
      uses: actions/upload-artifact@v2-preview
      with:
        name: amd64-windows-client
        path: /tmp/WORKSPACE/DEPLOY
  i686-windows-client:
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: |
        CONFIG_WIN_ARCH=i686
        . ./lib.sh &&
        RETRY sudo apt-get update &&
        mkdir -p /tmp/WORKSPACE &&
        pushd /tmp/WORKSPACE &&
        install_minetest_mingw_builddeps__and__build__ubuntu1604 &&
        mkdir -p /tmp/WORKSPACE/DEPLOY/client/windows/i686 &&
        cp ./minetest/minetest.zip /tmp/WORKSPACE/DEPLOY/client/windows/i686 &&
        popd
    - name: Publish
      uses: actions/upload-artifact@v2-preview
      with:
        name: i686-windows-client
        path: /tmp/WORKSPACE/DEPLOY
